apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: devopshint
          image:  891377194950.dkr.ecr.ap-south-1.amazonaws.com/devopshint:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs
# spec:
#   selector:
#     app: nodejs
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer
